#!/usr/bin/env node
// Creates apps/web/.env.local for local development (gitignored).
// - a throwaway ES256 key pair (private key goes in JWT_PRIVATE_KEY, base64 PKCS#8 PEM)
// - a random AUTH_SECRET
// - MOCK_BACKEND=true + DEMO_MODE=true so the UI works without the Python backend
// The matching public key is printed so you can paste it into the backend's env.
import { generateKeyPairSync, randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(root, ".env.local");
const force = process.argv.includes("--force");

if (existsSync(target) && !force) {
  console.log(".env.local already exists. Re-run with --force to overwrite.");
  process.exit(0);
}

const { privateKey, publicKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
const privPem = privateKey.export({ type: "pkcs8", format: "pem" }).toString();
const pubPem = publicKey.export({ type: "spki", format: "pem" }).toString();

const lines = [
  "# Generated by scripts/setup-dev-env.mjs — local development only, never commit.",
  "BACKEND_URL=http://localhost:10000",
  `JWT_PRIVATE_KEY=${Buffer.from(privPem).toString("base64")}`,
  `AUTH_SECRET=${randomBytes(32).toString("base64url")}`,
  "DEMO_MODE=true",
  "MOCK_BACKEND=true",
  "NEXT_PUBLIC_GITHUB_URL=https://github.com/Sohail-5678/returnpilot",
  "# AUTH_GITHUB_ID=",
  "# AUTH_GITHUB_SECRET=",
  "# ADMIN_GITHUB_USERS=",
  "# REVIEWER_GITHUB_USERS=",
  "",
];
writeFileSync(target, lines.join("\n"), { mode: 0o600 });

console.log("Wrote", target);
console.log("\nPublic key for the backend (JWT_PUBLIC_KEY, base64 SPKI PEM):\n");
console.log(Buffer.from(pubPem).toString("base64"));
